version: '3.7'
services:
  client:
    container_name: ${app_name}_${instance_id}_web
    image: node:alpine3.11
    stdin_open: true # needed for dev as react-scripts exits after start
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - './code/:/home/node/app'
      - nodemodules:/home/node/app/node_modules
    ports:
      - ${client_host_web_port}:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run start  
  node_modules_container:
    image: node:alpine3.11
    user: "root"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - nodemodules:/home/node/app/node_modules  
      - ./code/:/home/node/app
    container_name: "${app_name}_${instance_id}_node_modules_builder"
    command: npm i         
volumes:
  nodemodules:
    external: true
    name: ${app_name}_nodemodules_${instance_id}    