FROM ubuntu:16.04

ENV DEBIAN_FRONTEND noninteractive

# Install packages
ADD ./provision/laravel/provision.laravel.sh /provision.laravel.sh

ADD ./provision/supervisor/supervisor.conf /etc/supervisor/conf.d/supervisor.conf

RUN chmod +x /*.sh

RUN ./provision.laravel.sh

WORKDIR /var/www/app

EXPOSE 80 22 35729 9876
CMD ["/usr/bin/supervisord"]
