version: '3.7'
services:
  web:
    container_name: "${app_name}_${instance_id}_web"
    build:
      context: .
      dockerfile: "./provision/laravel/Dockerfile.laravel"
    working_dir: /var/www/app
    restart: unless-stopped
    ports:
      - "${server_host_web_port}:80" # web
      - "${server_host_ssh_port}:22" # ssh
    volumes:
     # - ~/.composer:/home/homestead/.composer # composer caching
     # - ~/.gitconfig:/home/homestead/.gitconfig # Git configuration ( access alias && config )
      - ./code:/var/www/app # all apps
      - ./provision/nginx/sites-enabled:/etc/nginx/sites-enabled # nginx sites ( in case you recreate the container )
      - ./provision/nginx/ssl:/etc/nginx/ssl
    links:
      - mysql
    networks:
      - changeme_api_env_network
    depends_on:
      - mysql
  mysql:
    container_name: "${app_name}_${instance_id}_database"
    build:
      context: .
      dockerfile: "./provision/mysql/Dockerfile.mysql"
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports: 
      - 3306:3306
    volumes:
      - /var/lib/mysql
    networks:
      - changeme_api_env_network
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: changeme
networks:
  changeme_api_env_network:
      driver: bridge
      name: changeme_api_env_network